### ISSUE TITLE
Version tagging

### ISSUE THREAD

**Issue by jmervine** [splunk/docker-splunk#116]
On hub.docker.com, there's a 7.2.3 release that was cut about a month ago. However, there's no git tag to match. It would be really helpful to be able to compare what's on hub.docker.com, with the current repo state. E.g.

https://github.com/splunk/docker-splunk/compare/<version_tag>..develop

**Comment by nwang92** [comment]
+1, this seems like a standard that would be good to incorporate. I'll see if I can go back through history and add the corresponding version tags to the proper commits.

**Comment by nwang92** [comment]
Went through history and added tags that lined up with when we pushed images. There might be some issues with <=7.2.1 because we started to use "develop" for development instead of "master". Hopefully things should line up though. We also started incorporating git tagging with our release process going forward, so this should be smoother in the future.

**Comment by jmervine** [comment]
Thank you!
