### ISSUE TITLE
Disable terminal colors from ansible output

### ISSUE THREAD

**Issue by outcoldman** [splunk/docker-splunk#140]
Running on ECS - logs from the containers are getting forwarded to CloudWatch with terminal escape codes, which just adds additional indexing cost and none-human-readable stuff.

<img width="1156" alt="screen shot 2019-03-04 at 1 51 35 pm" src="https://user-images.githubusercontent.com/597158/53762447-60f8c780-3e85-11e9-9b56-e39ac1199be3.png">

**Comment by timoguin** [comment]
Setting the `ANSIBLE_NOCOLOR` environment variable to true should take care of this.

**Comment by arctan5x** [comment]
Since we use ANSIBLE_FORCE_COLOR (force_color in ini) inside of ansible.cfg, setting ANSIBLE_NOCOLOR shouldn't work.

If you add ANSIBLE_FORCE_COLOR=0 to the container environment,  this will override our default option to remove color. I have tested it and it works well. Closing this issue for now, if you need  extra support, feel free to reopen this issue.
