### ISSUE TITLE
Container didn't start ansible play

### ISSUE THREAD

**Issue by tomzheng** [splunk/docker-splunk#212]
Hi 

I start docker run with below command:

docker run -d -p 8000:8000 -e "SPLUNK_START_ARGS=--accept-license" -e "SPLUNK_PASSWORD=password" -e "SPLUNK_HOME=/opt/splunk" -e "SPLUNK_DEFAULTS_URL=http://splunk-defaults/default.yml" -e "SPLUNK_ROLE=splunk_search_head"  -e "SPLUNK_CLUSTER_MASTER_URL=master" -e "SPLUNK_INDEXER_URL=indexer-0,indexer-1,indexer-2" -e "SPLUNK_SEARCH_HEAD_URL=search-0,search-1" -e "SPLUNK_DEPLOYER_URL=deployer" -e "SPLUNK_SEARCH_HEAD_CAPTAIN_URL=captain" -e "DEBUG=true" --name splunk splunk/splunk:latest

But it didn't start run ansible play to configure the splunk.

411db1f8bf8176f29ff86e2e03c1924725d8b878c5b0ea86549b197157ab79d3
tzheng@tzheng-MBP-6BBF4:~/kubernetes/docker-splunk/test_scenarios/kubernetes$docker logs splunk
ansible-playbook 2.8.0
  config file = /opt/ansible/ansible.cfg
  configured module search path = [u'/opt/ansible/library', u'/opt/ansible/apps/library', u'/opt/ansible/ansible_commands']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 2.7.16 (default, Apr  6 2019, 01:42:57) [GCC 8.3.0]

I am using docker 18.09.2, run on macos 10.13.6, use docker-splunk, develop branch

**Comment by bb03** [comment]
@tomzheng  Does the problem still exist?  Also, can you send us the ```docker logs``` output from the container if this happens again.  Thanks

**Comment by nwang92** [comment]
I think the problem here is the env var `SPLUNK_DEFAULTS_URL=http://splunk-defaults/default.yml`.

This needs to be a resolvable host, and upon startup our dynamic inventory script will try to download the `default.yml` from this URL. If this host does not exist (which I'm guessing is the case because it looks like it's coming from our on the k8s examples) or there are errors fetching the file, it will retry (will need to check the code again, it's either indefinite or there may be an upper limit to the retry attempts).

In any case, that's probably what you're seeing here. I'd recommend looking at some of examples here in terms of getting started: https://github.com/splunk/docker-splunk/blob/develop/docs/EXAMPLES.md
