### ISSUE TITLE
Create a new splunk container with pre-loaded indexes 

### ISSUE THREAD

**Issue by naggappan** [splunk/docker-splunk#214]
I tried the following and it works,
* Create a new splunk container
* push some logs into the splunk and that goes to separate index what I have created
* Now zip the entire /opt/splunk folder and copied to a new container and extracted in /opt/splunk
* Reports and data are available in the new splunk

Below is not working:
* I tried to do this copy of /opt/splunk into the container by creating a new docker image from the base image of splunk
* Now when the container is starting it fails in the ansible initialization

Reason for doing it:
* It takes lots of time to push the data to splunk
* So for some demo purpose we need some pre-loaded data and charts when I create the splunk itself

How can I make it happen? I know that updating the entire /opt/splunk folder is not good way but that at-least works manually .

**Comment by matthewmodestino** [comment]
Instead of dealing with the entire opt directory, you should simply make a splunk app that can be loaded with the app install plays.

https://github.com/splunk/docker-splunk/blob/develop/docs/advanced/APP_INSTALL.md
 

Here is an example standalone yaml that I use, where I seed my apps in /tmp on the container build, so that on install they are ready to go.

https://github.com/matthewmodestino/container_workshop/tree/master/splunk_k8s/standalone

Heres how I build the image:

https://github.com/matthewmodestino/container_workshop/tree/master/container_images/container_workshop


As for the demo data, you can seed that data in files in your app and just create inputs in your app so that we will ingest the sample data as soon as Splunk starts.

**Comment by nwang92** [comment]
Additionally, there is also a way to add your own custom config file - which in this case would be a indexes.conf with the proper content: https://github.com/splunk/docker-splunk/blob/develop/docs/ADVANCED.md#create-custom-configs

Closing issue as there's multiple workarounds (apps, custom confs, downstream images) provided.
