### ISSUE TITLE
Can a container be configured with multiple SPLUNK_ROLE s? 

### ISSUE THREAD

**Issue by kundeng** [splunk/docker-splunk#226]
I configured a deployer with role splunk_deployer but it does not seem it is configured to as a searchhead of an index cluster by default.

**Comment by arctan5x** [comment]
We do not have a support for multiple SPLUNK_ROLE for an instance. In your case, your deployer won't act as a search head.

**Comment by kundeng** [comment]
Thanks for confirming this.  There is another github project based on vagrant which supports virtualbox and AWS and will support docker in the future.  It solves those 2 issues that I have encountered: 1. multiple-role 2.  do not re-provision after first-run unless forced.  

It is here:  https://github.com/splunkenizer/Splunkenizer

**Comment by nwang92** [comment]
Although this is probably possible, our thinking here was that "containers are cheap" so it should be fairly inexpensive to include an additional container in your deployment to act as a specific role. On bare-metal or cloud, you might want to condense some roles in order to reduce cost and overhead, however even then only specific role combinations are supported or even recommended. 

In any case, I don't believe we plan to support multi-role (unless absolutely necessary or there's a compelling reason) but you could fork https://github.com/splunk/splunk-ansible and modify the roles to include tasks yourself.
