### ISSUE TITLE
Is there a way to stop ansible from reprovisioning the container?

### ISSUE THREAD

**Issue by kundeng** [splunk/docker-splunk#227]
I was able to create a test environment with  docker-compose.  The details are not important, it contains a 3 node search head cluster, 4 node index cluster, 1 cm, 1 lm, and 1 deployer.  

I noticed that the deployer is not configured to be a search head.  This was filed as an issue at #226 

After that, I made some changes to the environment.  My goal is to manually converting this environment into a multi-site environment.  At some point, I decided to stop and restart the stack using 
docker-compose. 

When I restart the stack,  I noticed that ansible is  re-provisioning the nodes that are already provisioned. 

I want to know whether there is an option to skip the reprovisioning once the creating-time provisioning is successful.  Or at least reprovisioning should be skipped on all nodes that are previously successful provisioned.    This is because reprovisioning don't always work, and depending what changes are made to the existing containers and to the docker-compose scripts,  some nodes end up failing (ansible) provisioning and splunkd exits.   This results in having to completely destroying and reinstalling everything. 

Does such an option of skipping ansible for provisioned nodes exist?   This seems to be the default behavior for vagrant systems as well.  Thanks!

**Comment by arctan5x** [comment]
We have logic to skip a lot of provisioning scripts through an Ansible check. If you look here (https://github.com/splunk/splunk-ansible/blob/develop/roles/splunk_common/tasks/main.yml), first_run is a variable that controls whether the provisioning scripts execute or not. "first_run" variable is set through get_facts.yml where it checks if your splunk secret folder exists. With this context, what are the exact commands are you running?

**Comment by kundeng** [comment]
It seems that the first_run variable is only skipping some of the tasks but not every task?  

I think the logic should be setting a provisioned flag or variable after the completion of the first run. 

I have described a concrete scenario in the above.  My use case may not be the most representative example of why people make changes to the environment after it is setup but here it is: 

I set up a single-site environment,  after that,  I'm manually converting it to a multi-site environment.  As I emphasized,  I'm doing it to practice for architect exam,  but  others might setup a docker based semi-permanent environment as their test environment and thus they may want to make incremental changes from time to time.

**Comment by nwang92** [comment]
In general, we've tried to make the combination of settings in the default.yml + env vars to be as idempotent as possible - I think there are still a few edge cases, but the goal is to make the application configuration as declarative as possible. 

For your specific case, since you're using these containers as full playground instances, I would actually recommend you run `docker run ... splunk/splunk no-provision`. This stands up the container (with any env vars you may have set) but it does not start the ansible playbook provisioning process. 

You can then proceed to exec into the container and run `/sbin/entrypoint start-and-exit` yourself to manually kick off the "first-time" run to stand up Splunk in whatever way you'd like. For your experimental/learning purposes, this may be for the best because when the container dies or restarts, since it was started with the `no-provision` argument, it won't try to run ansible again. The caveat here is of course that if the container does die, you'll need to exec in and start Splunk back up.

**Comment by nwang92** [comment]
Closing this, but feel free to re-open if you want to continue the discussion!
