### ISSUE TITLE
Universal Forwarder No Longer Copies App

### ISSUE THREAD

**Issue by Adam2Marsh** [splunk/docker-splunk#295]
Good Evenyone,

Recently upgraded our universalforwarder image from 6.4.3 to 7.3.3 to fix the datetime xml issue. During this change I wanted to test 7.3.3 would work with an updated K8s Cluster as we plan to upgrade early next year.

One of the things changing in the later versions of k8s is the ReadOnly Confimap which means we can't volume mount our configuration directly into the /etc/apps folder as the container will fail trying to chown the app.

I found the following splunk answers - [https://answers.splunk.com/answers/626964/kubernetes-194-breaking-changes-universal-forwarde.html](https://answers.splunk.com/answers/626964/kubernetes-194-breaking-changes-universal-forwarde.html) which suggested to mount our app in a different folder and the container will copy into the correct folder. This worked fine in 6.4.3 but doesn't work in 7.3.3

When checking documentation I couldn't see anytihng about copying an app from 1 directory to another unless its tar up. Can anyone confirm if the old funtionatilty still exists? Or has this been removed for the new methods?

Thanks in advanced.

**Comment by nwang92** [comment]
There's been a considerable overhaul from the previous 6.4.3 images to the images you see in this repo now - we've only recently started supporting Splunk in Docker since 7.2.x.

Anyways, regarding your app installation problems we're trying to standardize on the following approaches:
- Mount directory (unarchived) into `/opt/splunk/etc/apps/` but obviously this doesn't work for your use case
- Mount archived version of your app into a separate location (ex: `/tmp/apps/app.tgz`) and instructing the Splunk container to install it at runtime (ex: `docker run ... -e SPLUNK_APPS_LOCATION=/tmp/apps/app.tgz ... splunk/splunk`)
- Host archived version of your app in some artifact storage solution (Artifactory, nginx webserver, etc.) and instructing the Splunk container to download it at runtime (ex: `docker run ... -e SPLUNK_APPS_LOCATION=http://webserver/app.tgz ... splunk/splunk`)

The `SPLUNK_APPS_LOCATION` also supports multiple apps if you choose to install a variety of apps as well, using something like `SPLUNK_APPS_LOCATION=http://webserver/app1.tgz,http://newserver/app2.tgz,/tmp/apps/app3.tgz`

**Comment by nwang92** [comment]
The only means of installing an app from an untarred source would be option #1 but that doesn't seem to be possible given the permission lock on RO configmaps.
