### ISSUE TITLE
Splunk "restarts" during container startup

### ISSUE THREAD

**Issue by ryanfaircloth** [splunk/docker-splunk#322]
While running a standard single instance test with HEC enabled the container will "restart". This appears to be caused by using restart after enabling input ports via the API. Rather than enable ports this way produce the appropriate inputs.conf entries as files prior to starting Splunk the first time. The impact of this is the inability to "trust" that a successful login or connection indicates readiness.

**Comment by nwang92** [comment]
Sorry it's taken me a bit to get to this - the problem is the s2s input uses `notify` to trigger a restart - which you would want if you were running these plays against a running Splunk instance. 

But for the Docker case, this happens before Splunk is running. Ideally the "Splunk Start" task clears this event but it does not seem like that's an option. Let me play around with it and see if I can make some tweaks.

**Comment by nwang92** [comment]
Done here https://github.com/splunk/splunk-ansible/pull/406

This will be out in the next release (8.0.3).
