### ISSUE TITLE
repFactor is set to 0 when variables for indexer cluster are set

### ISSUE THREAD

**Issue by ghost** [splunk/docker-splunk#331]
Currently working on setting indexer clustering in k8s and faced with the issue that repFactor is set to 0 even if variables for adjusting indexer cluster are specified. In the result all nodes(master/SH/indexer) configured for indexer clustering as expected, but indexes are not replicated between indexers.

**Comment by nwang92** [comment]
Can you share what your yaml/s looks like for how you're setting up the Splunk cluster?

**Comment by ghost** [comment]
Indexer config:  
    containers: 
        - name: indexer
          image: splunk/splunk:latest
          env:    
            - name: SPLUNK_HOME
              value: /opt/splunk
            - name: SPLUNK_START_ARGS
              value: "--accept-license"
            - name: SPLUNK_ROLE
              value: splunk_indexer
            - name: SPLUNK_CLUSTER_MASTER_URL 
              value: master
            - name: SPLUNK_INDEXER_URL 
              value: indexer-0,indexer-1,indexer-2
            - name: SPLUNK_SEARCH_HEAD_URL
              value: search
            - name: SPLUNK_IDXC_REPLICATION_FACTOR
              value: "3"
            - name: SPLUNK_PASS4SYMMKEY
              value: "test"
            - name: SPLUNK_IDXC_PASS4SYMMKEY
              value: "test"
            - name: SPLUNK_IDXC_SEARCH_FACTOR
              value: "3"
            - name: SPLUNK_PASSWORD # admin passowrd 
              valueFrom:
                secretKeyRef:
                  name: splunk-password
                  key: password
            - name: DEBUG
              value: "true"

**Comment by nwang92** [comment]
Thanks! Where are you seeing the repl factor being set to 0? Based on your YAML above:
```
containers:
- name: indexer
   image: splunk/splunk:latest
   env:
   - name: SPLUNK_HOME
      value: /opt/splunk
   - name: SPLUNK_START_ARGS
      value: "--accept-license"
   - name: SPLUNK_ROLE
      value: splunk_indexer
```
This instance is an indexer that will connect to the cluster master at the host `master`. The indexer itself might not be aware of the replication factor, as I believe it's the cluster master role that is responsible for setting and ensuring the desired repl + search factor is met. So you'll want to make sure that you are setting `SPLUNK_IDXC_REPLICATION_FACTOR` on the master's config.

**Comment by ghost** [comment]
On master node: 

cat /opt/splunk/etc/system/default/indexes.conf | grep repFactor
repFactor = 0

Also as understood indexes.conf should be distributed across indexers. Therefore this config will be the same on all indexers.
Master node config:

      containers:
        - name: master
          image: splunk/splunk:latest
          env:    
            - name: SPLUNK_HOME
              value: /opt/splunk
            - name: SPLUNK_START_ARGS
              value: "--accept-license"
            - name: SPLUNK_ROLE
              value: splunk_cluster_master
            - name: SPLUNK_CLUSTER_MASTER_URL
              value: master
            - name: SPLUNK_INDEXER_URL
              value: indexer-0,indexer-1,indexer-2
            - name: SPLUNK_SEARCH_HEAD_URL
              value: search
            - name: SPLUNK_PASS4SYMMKEY
              value: "test"
            - name: SPLUNK_IDXC_PASS4SYMMKEY
              value: "test"
            - name: SPLUNK_IDXC_SEARCH_FACTOR
              value: "3"
            - name: SPLUNK_IDXC_REPLICATION_FACTOR
              value: "3"
            - name: SPLUNK_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: splunk-password
                  key: password
            - name: DEBUG
              value: "true"

**Comment by nwang92** [comment]
I don't think you want to look at `/opt/splunk/etc/system/default/indexes.conf` - these are all the default configurations for the Splunk system that you get out-of-the-box. 

If you look at `/opt/splunk/etc/system/local/server.conf`, you'll see the search factor reported there:
```
[clustering]
cluster_label = idxc_label
mode = master
pass4SymmKey = $7$0TTRASLyfI6a3hHvI6x76j+oyWznDVBWXBnHSCJSQ5pg7N2N/dq03ikyvddM1iQJOiiZbjaG4IwaGSY9Quczaw==
search_factor = 3
```

I'm not certain where the replication factor is stored - I was under the impression it was here as well. But if you log into SplunkWeb of the cluster master, and navigate to "Settings > Indexer Clustering" you can see all the info there. Example:
<img width="772" alt="Screen Shot 2020-03-11 at 10 07 33 AM" src="https://user-images.githubusercontent.com/6201822/76443775-35ee6100-6380-11ea-9ff9-545e430c04dd.png">

**Comment by ghost** [comment]
Okay,it works from my side as well. Replication factor that you show on the screenshot shows how may copies of the data should be presented in clustered indexers. repFactor as a variable(indexes.conf) shows whether  index/es should be replicated.
And that's the key point Replication factor is set and therefore in Splunk UI you can see it's value the problem is in repFactor variable. By default it's set to 0 even in cluster mode that prevents indexes to replicate between each other.
You can check this value using the request:
```
| rest services/data/indexes
```
You can create new index and check that it's value is 0.
This value can be changed in /opt/splunk/etc/system/local/indexes.conf and restarting the endpoint,but haven't tested it on all nodes yet,also haven't that replication will work after it.
My message that this should be configured when you specify variables for clustering,as for now you need to think how to add your indexes.conf file and then restart Splunk endpoint and I have no idea how and it will be cool if it will be automated.

**Comment by ghost** [comment]
After setting this param on all indexers master started to show new indexes:
![image](https://user-images.githubusercontent.com/31631542/76506417-31977600-645c-11ea-8439-503358eb0b68.png)
Now digging in why replication data is not spread across other indexers.




Update:
It only seems to work if the index is represented on all the indexes where the data should be replicated, otherwise it shows an error that the indexer cannot be found on the remote indexer.
![image](https://user-images.githubusercontent.com/31631542/76516255-21879280-646c-11ea-93b8-0785ecaaccd2.png)
replication_test was created on all indexers.
replx was create only on one node. 





Update:
You can also set this param in $SPLUNK_HOME/etc/master-apps/_cluster/local/indexes.conf and distribute it.

**Comment by nwang92** [comment]
Ah, I see what you mean. Out of the box, Splunk doesn't come with many indexes for you - I believe outside of the privately used `_`-prefixed indexes (ex. `_internal`, `_audit`, etc.), you only get `index=main`, `index=summary`, and `index=history`. 

After that, index creation is a responsibility for the user. Typically, we recommend doing this in the following ways:
* Follow [custom conf creation](https://github.com/splunk/docker-splunk/blob/develop/docs/ADVANCED.md#create-custom-configs) for your `indexes.conf`. Once this is part of the `default.yml` that gets shared to all the containers of your Splunk deployment, the provisioning should handle distributing it via bundle push
* Create a [Splunk app](https://docs.splunk.com/Documentation/Splunk/latest/Admin/Whatsanapp) which consists of a collection of various *.conf files, where you can modify exactly how your indexes are configured. You can [pass this in](https://github.com/splunk/docker-splunk/blob/develop/docs/EXAMPLES.md#create-standalone-with-app) via a file-on-disk or URL and the container will install it and distribute it amongst the cluster.

With regards to your approach, it works but has a few limitations (as you've seen). Whenever you create a resource like an index via the Splunk UI, you're only creating it locally on that particular instance. This which is why you see the available on that single node. Outside of the lack of data replication, you've also made changes to that single indexer but not the entire group of indexers, so now it's a special snowflake in the indexer tier. If you haven't set up persistent volumes, anytime that indexer dies you will end up losing the index created on it.

Additionally, my guess is Splunk by default set `repFactor` in `system/default/indexes.conf` to be disabled. You can change this using the custom-config file option as mentioned above, but I'm not sure if there are any unintended consequences from this. Splunk configurations work as a layered system, so what ends up happening is configs in `local` overwrite those in `default`. But also changes made in `system` propagate across the entire Splunk instance, which may also impact other apps or add-ons you install (these can be found within `/opt/splunk/etc/apps/`). 

So as far as changing `repFactor` by default when a cluster is setup, I don't think this is an approach we want to take - mainly because I'm uncertain of what the downstream implications would be for the ecosystem of Splunk apps, developed internally or externally. The most-recommended approach you'll hear is to create your own Splunk app with all the config files you need to tailor Splunk Enterprise for your use case. Then you can version-control, build, rollback any changes with ease.

**Comment by ghost** [comment]
What can you recommend for rapidly changing environment where changes occurs rather often(create/delete/change index or it's config)?
It sounds a bit tricky to change config every time you have changes and restart endpoint after it.

**Comment by nwang92** [comment]
Gotcha - if you plan on making changes via UI or API calls, my recommendation would be to make sure `/opt/splunk/etc` is backed by some persistent volume. 

All configuration changes would exist in that directory (system config changes, new users, new apps, app config changes, etc). As long as you can guarantee that persistent storage block follows your Splunk instance around, you don't necessarily need to do a rolling update to get the changes reflected.

Having said that, I suppose usage might fall into two stages of deploying some third party application? Initially, you might not know what knobs you want to tweak to get that app running the way you want it to. During this stage, I would expect you want the environment to support rapid changes + short iteration cycles which is where the persistent storage tier would help. However, once you have the app configured the way you want, you may never want to change it/only support infrequent changes. This may be better suited for the whole app process I mentioned above because this would allow you to declare how you want your Splunk instance to run upfront.

The best solution is probably a combination of both though, so you can support live changes but also making sure to backport the change you made into some configuration management system/version control so it is repeatable in the future.

**Comment by ghost** [comment]
Thanks for ideas,I'm mostly interested in the best way of index management(i.e new team want to be monitored in Splunk -> create a separate index for them and another team want to disable their index). How to manage them centrally and in the most automated way(as changing indexes.conf on master every time when changes happen is not so flexible).
I understand that you tried to describe this question in previous comment,but I don't have any other applications for now and trying to find a way to manage indexes on all indexers as automated and native way as it's possible.

**Comment by nwang92** [comment]
For that specific case, I would still recommend backing `/opt/splunk/etc` using some persistent volume so you can save the state of all indexes - this would allow you to support CRUD on all indexes, whether it be through the UI or REST API.

I'm assuming you're using an indexer cluster, so you have 1 cluster master and n indexers. The best way to distribute changes to indexes is to create a cluster bundle and apply it. You just need some mechanism to take your `indexes.conf` and put it inside `/opt/splunk/etc/master-apps/_cluster/local/` on the cluster master. After that, you can run the `splunk apply cluster-bundle` CLI on the cluster master and it will take care of sending the artifacts to the peers (or there's a [REST API you can POST](https://answers.splunk.com/answers/387133/how-to-create-index-using-rest-api-in-a-clustered.html) to trigger the bundle push).

As far as what that mechanism is to transfer the `indexes.conf` into `/opt/splunk/etc/master-apps/_cluster/local/`, we don't really have a good system for that - outside of the hooks for app installation and custom conf files. But that would require container restarts, which is what you're trying to avoid. The only thing I can think of is some combination of `cp`/`exec` calls, but that doesn't seem super friendly.

**Comment by nwang92** [comment]
I guess part of the problem is Splunk REST API doesn't inherently support a native mechanism to create configs/files in `etc/master-apps/_cluster/` - if this was possible, then you could more easily automate your problem using remote API calls.

**Comment by ghost** [comment]
Thanks a lot for your response. Is it possible somehow to contact you if I have new questions?

**Comment by nwang92** [comment]
Absolutely! You can use my Splunk email (nwang@splunk.com), the email in my Github profile, or even LinkedIn. I'm also in the #docker channel of the splunk-usergroups slack https://splunk-usergroups.slack.com/archives/C1RH09ERM if you wanna ping me directly through there. 

Going to close this since we've kinda went away from and beyond the issue issue.
