### ISSUE TITLE
Publish new version of Splunk Docker Image

### ISSUE THREAD

**Issue by outcoldman** [splunk/docker-splunk#44]
How often new images will be available at hub.docker.com?

I am looking forward to trying this https://github.com/splunk/splunk-ansible/pull/9, but seems like `splunk/splunk:7.2.0` was updated ~~16~~ ~~17~~ 18 days ago https://hub.docker.com/r/splunk/splunk/tags/

**Comment by mikedickey** [comment]
We plan to update the image as new versions of Splunk are released. We're also evaluating the feasibility of updating the image more frequently, in-between Splunk releases.

**Comment by outcoldman** [comment]
Mike, please consider enabling auto-build for the docker hub. As I understand there are no specific reasons for people to wait for a new release.

Also curious, how are you going to handle 7.3 and 7.2.x releases? Will this repo always provide the latest or it will support multiple minor versions?

**Comment by mikedickey** [comment]
We do plan to publish updates for all minor splunk releases (7.2.x). Being totally transparent: the reason we're not updating Docker hub more frequently right now is because it is a manual process. Automating this is at top of our TODO list.

We would like "latest" to represent the latest state of code here + latest Splunk release. Still ironing out details on best process for pushing all the other tags. Whatever we come up with, we'll document it when ready.

**Comment by outcoldman** [comment]
@mikedickey 7.2.1 is out for a week now, is it possible to get a new release out? Thanks!

**Comment by mikedickey** [comment]
@outcoldman it's been published
`docker pull splunk/splunk:7.2.1`

**Comment by mikedickey** [comment]
FYI 7.2.2 docker containers were pushed yesterday concurrent with the 7.2.2 release of Splunk. It's now part of our formal release process for Splunk Enterprise to concurrently publish container updates.
