### ISSUE TITLE
Avoid data loss incase of k8s pod restart ?

### ISSUE THREAD

**Issue by alnhk** [splunk/docker-splunk#447]
Hello - 
We are migrating from old splunk 6.5(running on AWS dedicated ec2 instance) to latest Splunk 8.1.1 (running on AWS EKS kubernetes 1.15)., we were able to spin up the splunk 8.1  on AWS EKS kubernetes, for my testing purpose, changed "Pause indexing if free disk space (in MB) falls below" from default 5000 to (say) 3000. The Splunk service is restarted from kubectl command, not from splunk UI, upon checking, the value gets over-written as default 5000 and not 3000. Is there something that incase of pod restart, how can we preserve the data and avoid losing the data ?  We have concern that the index data may go away incase of pod restart for example OOM or unexpected crash. Here are the steps we are able to reproduce : 
1. Create a K8s pod with splunk 8.1.1, all default (with PVC mounted on /opt/splunk/var and "splunk/splunk:latest" as well as "splunk/splunk:edge")
2. Install some apps (around 12 apps including slack notification, slack webhook etc)
3. Restore the indexed data 
4. Manually restart the splunk from UI - confirms all goods
5. Manually restart the POD from k8s using kubectl command - everything is gone (appears to be hard factory reset to "base").
6. Repeat point #2 and #3 , start the splunk, confirms all good,  add some process that eats off the memory in the splunk pod, OOM is hit and the pod is restarted itself, everything is gone. 

Is there anything how we can prevent this from losing the data despite presence of  "PersistentVolumeClaim" with "standard-retained" as well as "rolling-upgrade" as updatestrategy in  StateFulSet kind.

**Comment by nwang92** [comment]
You can refer to [these docs](https://github.com/splunk/docker-splunk/blob/develop/docs/STORAGE_OPTIONS.md) for storage persistence, but the TLDR of it is:
* Enable persistence over `/opt/splunk/etc` for configuration changes (like your free disk space setting)
* Enable persistence over `/opt/splunk/var` for indexed data

I'd also recommend using [SmartStore](https://docs.splunk.com/Documentation/Splunk/8.1.1/Indexer/AboutSmartStore) for some level of remote persistence as well. But since you're using Kubernetes/EKS, you may want to check out the [splunk-operator project](https://github.com/splunk/splunk-operator) which may have more options/knowledge around persistent volume choices.
