### ISSUE TITLE
splunk ingress ?

### ISSUE THREAD

**Issue by alnhk** [splunk/docker-splunk#463]
can you please include splunk ingress in kubernetes folder ? We were able to deploy the splunk to the kubernetes using "3idxc3shc1cm1lm1dep-pvc", however, splunk ingress seems to be hard to use , for instance, we had to always open this link as an example this below link works 
>  https://splunktest.example.com/en-US/account/login?return_to=%2Fen-US%2Fapp%2Flauncher%2Fhome 

When we log out, it redirects to 
> https://splunktest.example.com/en-US/account/login

When we re-login, it stucks at  and never moves forward 
> https://splunktest.example.com/en-US/

So, we had to always open this link (used to work): 
>  https://splunktest.example.com/en-US/account/login?return_to=%2Fen-US%2Fapp%2Flauncher%2Fhome 

We are using this simple ingress  as per , the detail of ingress yaml provided as per below link is not proven working., we tried both on DEV, test, staging and production AWS EKS., still very hard to use the URL.
> https://github.com/splunk/docker-splunk/issues/397

**Comment by nwang92** [comment]
Just a guess here, but this might be more of how the ingress controller is configured? If you're deploying multiple search heads in a search head cluster, you probably want to enable some form of sticky sessions so you're always directed to the same pod, if available. Otherwise, I imagine that's where you're seeing issues with re-logins getting stuck.

Alternatively, if you pin the ingress/service to just one role (ex: `splunk-search-captain-service`) I'm guessing you'll see that problem go away.

**Comment by nwang92** [comment]
Those ingress settings/annotations would depend on which ingress controller you're using.
