### ISSUE TITLE
sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?

### ISSUE THREAD

**Issue by gordondu99** [splunk/docker-splunk#683]
can you help below issue when docker run? thanks!

only user root (docker run -d -u root ) can avoid this.

PLAY [Run default Splunk provisioning] *****************************************

TASK [Gathering Facts] *********************************************************
fatal: [localhost]: FAILED! => {
    "ansible_facts": {},
    "changed": false,
    "failed_modules": {
        "ansible.legacy.setup": {
            "failed": true,
            "module_stderr": "sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?\n",
            "module_stdout": "",
            "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
            "rc": 1
        }
    }
}

MSG:

The following modules failed to execute: ansible.legacy.setup

**Comment by gordondu99** [comment]
find the root cause, thanks!

**Comment by cmellazchy** [comment]
Edit: NFS volumes are mounted to `/opt/splunkforwarder/etc` and `/opt/splunkforwarder/var` as PV where we do not have root access. So, I guess ansible isn't able to gather facts since it doesn't have root access(?).

@gordondu99 I'm running into the same issue while trying to deploy the container as a sidecar in our k8s cluster. What ended up being the root cause?
