### ISSUE TITLE
Add splunk user back to sudoers file

### ISSUE THREAD

**Issue by jmervine** [splunk/docker-splunk#74]
Please allow for optionally including the "splunk" user in the sudoers file. At the least, include a build arg, which enables it. Another option, would be to add the following lines back (removed in https://github.com/splunk/docker-splunk/pull/72/)
```
    && usermod -aG sudo ${SPLUNK_USER} \
    && sed -i -e 's/%sudo\s\+ALL=(ALL\(:ALL\)\?)\s\+ALL/%sudo ALL=NOPASSWD:ALL/g' /etc/sudoers \
```
And then include a something in the entrypoint.sh that removes them again, unless a flag is set to keep them.

Why? Under kubernetes, the `/opt/splunk/etc` directory is mounted with "root" as the owner. As such, splunk isn't able to install.

**Comment by jmervine** [comment]
cc @lephino

**Comment by lephino** [comment]
Please note to those on k8, there was a line to chown all of the var dir in the "pre-sudo" removal, that play is now gone, and you should add it on your own.  For a note, I added the base backage for ACL to the container, so you can now (baring the filesystem / volume mount type you use) support adding a base ACL to the var / etc directory, instead of eating time needed by  the permissions chown operation on entrypoint.

**Comment by jmervine** [comment]
@lephino I'm going to close this, now that #75 has been merged to develop.
