### ISSUE TITLE
Ansible does not restart splunk after app installation with SPLUNK_APPS_URL

### ISSUE THREAD

**Issue by outcoldman** [splunk/docker-splunk#92]
Not sure if SPLUNK_APPS_URL is supported, but I tried to use it to install an application from a local folder inside of the container. This application has some configurations, that require Splunk to be restarted. The app has been installed, but Splunk was not restarted 

<img width="475" alt="screen shot 2018-12-20 at 7 50 15 pm" src="https://user-images.githubusercontent.com/597158/50323834-7bc7bc80-0490-11e9-9088-e2702d37cc34.png">

**Comment by c3-rockyong** [comment]
you're right. https://github.com/splunk/splunk-ansible/blob/e71f66f9483784d18dbdd5958d2e38ad6b729965/roles/splunk_common/tasks/install_app.yml doesn't notify to restart splunkd. might want to open an issue there

were you able to use `SPLUNK_APPS_URL` at all? I bump into an issue with SSL cert verification when using `SPLUNK_APPS_URL`, tracking it down, I believe this is caused by Splunk turns on cert verification for S2S communication by default:

```
root@search-1:/opt/splunk/etc/system/default# grep sslVerifyServerCert *
server.conf:sslVerifyServerCert = true
```

Wonder if we can change this default setting or it's even safe to disable it

**Comment by nwang92** [comment]
Sorry, this fell off my radar but I can probably address this. 

@c3-rockyong what SSL issues were you seeing? Do you have an error log or way to reproduce it?

**Comment by c3-rockyong** [comment]
@nwang92: yes, you can do something like this:

```
curl -k -u<user:pass> -X POST \
  https://127.0.0.1:8089/services/apps/local \
  -d 'name=<insert_app_URL_here>&update=true&filename=true'
```

error message:
```
<?xml version="1.0" encoding="UTF-8"?>
<response>
  <messages>
    <msg type="ERROR">Unexpected error downloading update: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed - please check the output of the `openssl verify` command for the certificates involved; note that if certificate verification is enabled (requireClientCert or sslVerifyServerCert set to "true"), the CA certificate and the server certificate should not have the same Common Name.</msg>
  </messages>
</response>
```

**Comment by nwang92** [comment]
Got it, it looks like Splunk handles the http links passed into the `/services/apps/local` but not https. I'll get that fixed!

**Comment by nwang92** [comment]
Both issues regarding apps have been reworked and fixed here: https://github.com/splunk/splunk-ansible/pull/68

This should be out in the next maintenance release of Splunk (7.2.4).
